In [47]:
import numpy as np

In [30]:
#Ejemplo de lista. Las listas sonmodificables. Las listas son mutables
x=[3, 'rrr', 9, 77, 'hh', 6, 7]
x[1]='aaa'
print(x)
x[-2] # con esto espas pidiendo que te dé la penultima posicion 
type(x[1])    # con esto sabes que esta almacenado en esa variable

[3, 'aaa', 9, 77, 'hh', 6, 7]


str

In [17]:
#Ejemplo de tupla. Las tuplas NO son modificables. Las tablas son inmutables
x1=(3, 'rrr', 9, 77, 'hh', 6, 7)
#x1[1]='aaa'   Esto no se puede hacer porque es inmutable
print(x1[1])

rrr


In [29]:
#Usar la función range para crear listas
a = list (range(5))   #n=5 significa que tendrá 5 elementos 
print(a)
b = list (range( 5, 41, 5))  # range (star, stop, step) se pone en 41 para que escriban el 40
print(b)
type(b)
type(b[3]) 
b[3]      # b en la posicion 4 

[0, 1, 2, 3, 4]
[5, 10, 15, 20, 25, 30, 35, 40]


20

In [26]:
#Usar la función range para crear tuplas
m=tuple(range(5,41,5))   # range (star, stop, step)
print (m) 
type(m)


(5, 10, 15, 20, 25, 30, 35, 40)


tuple

In [34]:
#Hacer lista de acracteres 
l = list(range(10))
print(len(l))
L2 = [str(s) for s in l] #quien sbe que es s
l3 = [str("daf") for s in l]
l3

10


['daf', 'daf', 'daf', 'daf', 'daf', 'daf', 'daf', 'daf', 'daf', 'daf']

In [45]:
#Array Crea uun arreglo
import array           #array es una clase 
L = list(range(10))
A = array.array('i', L)  # array 1 clase array 2 objeto o método de la clase array estas llamando al método Array i indica que el arreglo es de enteros
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
#arreglos
c=np.array([1,4,8,2.7,9,8, 'c'])
type(c)
type(c[0])

numpy.str_

In [56]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 8) for i in [2, 4, 6,8, 12]])

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [ 4,  5,  6,  7,  8,  9, 10, 11],
       [ 6,  7,  8,  9, 10, 11, 12, 13],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [3]:
#lentitud de los ciclos 
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):        # def indica que vas a definir una función, values es la entrada de la función 
    output = np.empty(len(values))      # len es length i, e longitud 
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)    #Aqui asignas un valor a "values"
print(values)
compute_reciprocals(values)                  #Aqui mandas a llamar la función compute_reciprocals y le estas pasando el valor de values 

[6 1 4 4 8]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [6]:
#lentitud de los ciclos  
# No correr ciclo, muy lento
#big_array = np.random.randint(1, 100, size=1000000)
#%timeit compute_reciprocals(big_array)

2.87 s ± 68.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
#Reoganzar un vector en forma de matriz

x = np.arange(10).reshape((5, 2))
2 ** x

array([[  1,   2],
       [  4,   8],
       [ 16,  32],
       [ 64, 128],
       [256, 512]], dtype=int32)

In [20]:
#Operaciones aritmeticas con arreglos
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)      # negación 
print("x ** 2 = ", x ** 2)   #Exponenciacion
print("x % 2  = ", x % 2)    #modulo
np.add(x, 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


array([2, 3, 4, 5])

In [30]:
#Equivalencias de operaciones artiméticas con sus funciones 
#     lo mismo que arriba, pero con funciones 
x = np.arange(4)
print(np.add(x, 5))
print(np.subtract(x, 5))
print(np.negative(x))
print(np.multiply(x,2))
print(np.floor_divide(x, 2))
print(np.power(x, 2))
print(np.mod(x, 2))

[5 6 7 8]
[-5 -4 -3 -2]
[ 0 -1 -2 -3]
[0 2 4 6]
[0 0 1 1]
[0 1 4 9]
[0 1 0 1]


In [31]:
#Valor absoluto diferentes formas de obtenerlo 
x = np.array([-2, -1, 0, 1, 2])
abs(x)
np.absolute(x)
np.abs(x)
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

In [35]:
#Funciones trigonometricas 
theta = np.linspace(0, np.pi, 3)   # devuleve numeros espaciados, uniformemente en u intervalo especifico 
type(theta)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))        #saca el seno del arreglo theta
print("cos(theta) = ", np.cos(theta))        #saca el coseno del arreglo theta
print("tan(theta) = ", np.tan(theta))        #saca el tangente del arreglo theta
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(x) =  [0.63398387-2.30550903j 0.91761685-2.29991404j 1.57079633+1.3169579j
 0.        +0.88137359j]
arccos(x) =  [0.93681246+2.30550903j 0.65317947+2.29991404j 0.        -1.3169579j
 1.57079633-0.88137359j]
arctan(x) =  [1.448307  -0.15899719j 1.40992105-0.11750091j 1.10714872+0.j
 0.               +infj]


In [37]:
#exponentes y logaritmos
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))
#
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]
ln(x)    = [0.         0.69314718 1.09861229]
log2(x)  = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]


In [47]:
#Salidas especiales o salidas directas
x = np.arange(1, 6)                #hace un arreglo de 5 elementos, pero ya con valores incluidos
y = np.empty(5)                 #hace un arreglo de 5 elementos, pero sin valores 
np.multiply(x, 10, out=y)       #del arreglo x, multiplica sus elementos x10 y guardalo en y
print(y)

[10. 20. 30. 40. 50.]


In [45]:
x = np.arange(1, 6)
np.add.reduce(x)     # suma todos los elemntos del arreglo 
print(x)
print(np.add.reduce(x))

[1 2 3 4 5]
15
